name: Python CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'

defaults:
  run:
    working-directory: backend

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
      
      - name: Check formatting with Black
        id: black-check
        run: |
          source .venv/bin/activate
          black --check . || echo "formatting_needed=true" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: Auto-format with Black
        if: steps.black-check.outputs.formatting_needed == 'true' && github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          black .
      
      - name: Run Ruff linting
        id: ruff-check
        run: |
          source .venv/bin/activate
          ruff check . || echo "linting_needed=true" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: Auto-fix with Ruff
        if: steps.ruff-check.outputs.linting_needed == 'true' && github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          ruff check --fix .
      
      - name: Commit formatting changes
        if: (steps.black-check.outputs.formatting_needed == 'true' || steps.ruff-check.outputs.linting_needed == 'true') && github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: auto-format Python code with Black and Ruff'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          file_pattern: 'backend/**/*.py'
      
      - name: Final lint check
        run: |
          source .venv/bin/activate
          black --check .
          ruff check .
      
      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          pytest -v --cov=backend --cov-report=term-missing
      
      - name: Upload coverage reports
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/htmlcov/