name: Test Skip CI

on:
  pull_request:
  push:

jobs:
  debug-context:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Head Commit Message: ${{ github.event.head_commit.message }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Labels: ${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo "All commits in PR:"
          echo '${{ toJson(github.event.commits) }}'